export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_HOUSES_INIT = "FETCH_HOUSE_INIT";
export const FETCH_HOUSES = "FETCH_HOUSES";
export const FETCH_HOUSE_BY_ID = "FETCH_HOUSE_BY_ID";
export const DELETE_HOUSE = "DELETE_HOUSE";

export const FETCH_BOOKINGS_INIT = "FETCH_BOOKINGS_INIT";
export const FETCH_BOOKINGS = "FETCH_BOOKINGS";
